force-app/main/default/objects/Business_Receipt_Number__c/Business_Receipt_Number__c.object-meta.xml
<CustomObject>
    <description>This is a Unique number for Business Receipts</description>
    <label>Business Receipt Number</label>
    <nameField>
        <displayFormat>{YYYY}-NT{0000}</displayFormat>
        <label>Business Receipt Number Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Receipt Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Receipt_Number__c/fields/Tax_Receipt__c.field-meta.xml
<CustomField>
    <fullName>Tax_Receipt__c</fullName>
    <inlineHelpText>The Business Receipt that this number is related to</inlineHelpText>
    <label>Tax Receipt</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria. You can only apply Business Receipt Numbers to Business Receipts, not Charitable Tax Receipts</errorMessage>
        <filterItems>
            <field>Tax_Receipt__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business Receipt</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tax_Receipt__c</referenceTo>
    <relationshipLabel>Business Receipt Numbers</relationshipLabel>
    <relationshipName>Business_Receipt_Numbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Eligible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Amount__c</fullName>
    <formula>Amount -   Personal_Benefit_Amount_c__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field is automatically calculated on save. This is the Personal Benefit Amount subtracted from the Amount of the opportunity. This is the amount of the donation that CRA deemed tax-receptible</inlineHelpText>
    <label>Eligible_Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/Tax_Receipt__c.object-meta.xml
<CustomObject>
    <description>Tax Receipts.</description>
    <label>Tax Receipt</label>
    <nameField>
        <label>Tax Receipt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Receipt__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <inlineHelpText>The total amount received by the organization</inlineHelpText>
    <label>Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <inlineHelpText>The Address City for who this Tax Receipt is issued to</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/Date_Issued__c.field-meta.xml
<CustomField>
    <fullName>Date_Issued__c</fullName>
    <inlineHelpText>The date this Reciept was issued</inlineHelpText>
    <label>Date Issued</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/Eligible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Amount__c</fullName>
    <inlineHelpText>The amount of the donation that is eligible for charitable tax receipt</inlineHelpText>
    <label>Eligible Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <inlineHelpText>The Opportunity/Donation that this Receipt is related to</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/Personal_Benefit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Personal_Benefit_Amount__c</fullName>
    <inlineHelpText>The amount received by the organization that had a personal benefit or advantage. This portion is ineligible for a tax receipt.</inlineHelpText>
    <label>Personal Benefit Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <inlineHelpText>The address Postal Code for who this Tax Receipt is issued to</inlineHelpText>
    <label>Postal Code</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <inlineHelpText>The address province for who this Tax Receipt is issued to</inlineHelpText>
    <label>Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/Receipt_Number__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Number__c</fullName>
    <inlineHelpText>This is automatically set by the system. This is a Unique number for this Receipt.</inlineHelpText>
    <label>Receipt Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/Receipt_Rationale_Gift_Description__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Rationale_Gift_Description__c</fullName>
    <inlineHelpText>This is a short description of the gift that will appear on the Receipt. This is useful for describing In-Kind Gift appraisals or sales of Stock</inlineHelpText>
    <label>Receipt Rationale/Gift Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>The Street Address for who this Tax Receipt is issued</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/Tax_Year_Received__c.field-meta.xml
<CustomField>
    <fullName>Tax_Year_Received__c</fullName>
    <inlineHelpText>If this is a year end consolidated receipt this is the year the gifts were received in</inlineHelpText>
    <label>Tax Year Received</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <inlineHelpText>Who is this Tax Receipt for</inlineHelpText>
    <label>To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt_Number__c/Tax_Receipt_Number__c.object-meta.xml
<CustomObject>
    <description>A Unique number to be applied to charitable tax receipts</description>
    <label>Tax Receipt Number</label>
    <nameField>
        <displayFormat>{YYYY}-{0000}</displayFormat>
        <label>Tax Receipt Number Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Receipt Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Receipt_Number__c/fields/Tax_Receipt__c.field-meta.xml
<CustomField>
    <fullName>Tax_Receipt__c</fullName>
    <inlineHelpText>The Tax Receipt that this number is applied to</inlineHelpText>
    <label>Tax Receipt</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria. Tax Receipt Numbers can only be applied to Tax Receipts not Business Receipts</errorMessage>
        <filterItems>
            <field>Tax_Receipt__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tax Receipt</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tax_Receipt__c</referenceTo>
    <relationshipLabel>Tax Receipt Numbers</relationshipLabel>
    <relationshipName>Tax_Receipt_Numbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TaxReceiptTriggerHandler.cls
/**
 * @description       : Trigger handler for Tax_Receipt__c
 * @author            : kevin@kevinwaites.com
 * @last modified on  : 09-27-2020
 * @last modified by  : kevin@kevinwaites.com
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   08-06-2020   kevin@kevinwaites.com                Initial Version
**/

public with sharing class TaxReceiptTriggerHandler {

    //public with sharing class TaxReceiptTriggerHandler {
        
        private boolean isExecuting = false;
        private integer batchSize = 0;
        public static boolean isFromBatchJob;
        public static boolean isFromUploadAPI = false;
    
        public TaxReceiptTriggerHandler(Boolean isExecuting, integer size) {
            isExecuting = isExecuting;
            BatchSize = size;
        }
    
        /**
        * @description      : Updates the fields on a new Tax_Receipt__c stamping them with 
        *                     related fields from Opportunity and Account
        * @author           : kevin@kevinwaites.com
        * @param            : newTaxReceipts 
        **/
        public void onBeforeInsert(List<Tax_Receipt__c> newTaxReceipts) {
    
            Set<Id> opportunityIds = new Set<Id>();
    
            for(Tax_Receipt__c thisTR:newTaxReceipts) {
                if(thisTR.Opportunity__c != null) {
                    opportunityIds.add(thisTR.Opportunity__c);
                }
            }
    
            Map<Id, Opportunity> opportunityMap = new Map<Id, Opportunity>([SELECT ID, Name, Amount, Eligible_Amount__c, Personal_Benefit_Amount__c, npsp__Primary_Contact__c, npsp__In_Kind_Description__c, Account.BillingCity, Account.BillingCountry, Account.BillingStreet, Account.BillingState, Account.BillingPostalCode, Account.Name  FROM Opportunity WHERE Id IN:opportunityIds]);
            List<Tax_Receipt_Number__c> trnList = new List<Tax_Receipt_Number__c>();
            List<Business_Receipt_Number__c> brnList = new List<Business_Receipt_Number__c>();
            for(Tax_Receipt__c tr:newTaxReceipts) {
                if(opportunityMap.containsKey(tr.Opportunity__c)) {
                    try {
                        Opportunity oppty = opportunityMap.get(tr.Opportunity__c);
                        tr.Amount__c = oppty.Amount;
                        tr.Name = oppty.Name + ' - Receipt';
                        tr.City__c = oppty.Account.BillingCity;
                        tr.Date_Issued__c = Date.today();
                        tr.Eligible_Amount__c = oppty.Eligible_Amount__c;
                        tr.Personal_Benefit_Amount__c = oppty.Personal_Benefit_Amount__c;
                        tr.Postal_Code__c = oppty.Account.BillingPostalCode;
                        tr.Province__c = oppty.Account.BillingState;
                        tr.Street__c = oppty.Account.BillingStreet;
                        tr.Receipt_Rationale_Gift_Description__c = oppty.npsp__In_Kind_Description__c;
                        
                        
                        if(oppty.npsp__Primary_Contact__c != Null){
                            tr.To__c = oppty.Npsp__Primary_Contact__c;
                        } else {
                            tr.To__c = oppty.Account.Name;
                        }
    
                        if(oppty.Eligible_Amount__c > 0) {
                            Tax_Receipt_Number__c trn = New Tax_Receipt_Number__c( Tax_Receipt__c = tr.Id);
                            tr.Receipt_Number__c = trn.Name;
                            trnList.add(trn);
                        } else {
                            Business_Receipt_Number__c brn = New Business_Receipt_Number__c( Tax_Receipt__c = tr.Id);
                            tr.Receipt_Number__c = brn.Name;
                            brnList.add(brn);
                        }
                        
                        // TODO: Add to Tax Receipt
                        // t.Number_of_Gifts = 
                        // t.Receipt_Number__c = 
                        // t.Receipt_Rationale_Gift_Description__c = 
                        // t.Tax_Year_Received__c = 
                        
                        
                    } catch (Exception e) {
                        System.debug('Error setting fields on this record:  ' + e.getMessage());
                        System.debug('On Line:  ' + e.getLineNumber());
                        tr.addError('Unable to update fields');
                    }
                }
            }
    
            if(!trnList.isEmpty()) {
                // Strip fields that are not creatable
                SObjectAccessDecision decision = Security.stripInaccessible(
                    AccessType.CREATABLE,
                    trnList);
                try{
                    insert decision.getRecords();
                } catch(NoAccessException e) {
                    system.debug(e.getMessage());
                }
                
                // Print removed fields
                System.debug(decision.getRemovedFields());
            }
            
            if(!brnList.isEmpty()) {
                // Strip fields that are not creatable
                SObjectAccessDecision decision = Security.stripInaccessible(
                    AccessType.CREATABLE,
                    brnList);
                try{
                    insert decision.getRecords();
                } catch(NoAccessException e) {
                    system.debug(e.getMessage());
                }
                
                // Print removed fields
                System.debug(decision.getRemovedFields());
            }
        }
    
        public void onAfterInsert(List<Tax_Receipt__c> newTaxReceipt) {
            system.debug('Tax Receipt Trigger on After Insert');
        }
    
        public void onAfterUpdate( List<Tax_Receipt__c> newTaxReceipt, List<Tax_Receipt__c> oldTaxReceipt, Map<ID, Tax_Receipt__c> newTaxReceiptMap, Map<ID, Tax_Receipt__c> oldTaxReceiptMap ) {
            system.debug('Tax Receipt Trigger On After Update');
        }
    
        public void onBeforeUpdate( List<Tax_Receipt__c> newTaxReceipt, List<Tax_Receipt__c> oldTaxReceipt, Map<ID, Tax_Receipt__c> newTaxReceiptMap, Map<ID, Tax_Receipt__c> oldTaxReceiptMap ) {
            system.debug('Tax Receipt Trigger On Before Update');
        }
    
        @future
        public static void onAfterUpdateAsync(Set<ID> newTaxReceiptIDs) {
    
        }
    
        public boolean isTriggerContext {
            get { return isExecuting; }
        }
    
        public boolean isVisualforcePageContext {
            get{ return !IsTriggerContext; }
        }
    
        public boolean isWebServiceContext {
            get{ return !IsTriggerContext; }
        }
    
        public boolean isExecuteAnonymousContext {
            get{ return !isTriggerContext; }
        }
    
        // TODO: upgrade the app to use Custom Metadata to manage the receipt numbers
        // These 2 methodsd don't work 
        // you can't use DML statments on Custom Metadata
        // private Decimal getNextTaxReceiptNumber() {
        //     Decimal nextNum = 0;
        //     try{
        //         Tax_Receipt_Number_meta__mdt myMeta = [SELECT Next_Number__c FROM Tax_Receipt_Number_meta__mdt WITH SECURITY_ENFORCED];
        //         nextNum = myMeta.Next_Number__c;
        //     } catch(System.QueryException qe) {
        //         System.debug(qe.getMessage());
        //     }
        //     return nextNum;
        // }
    
        // private void incrementTaxReceiptNumber() {
        //     try {
        //         Tax_Receipt_Number_meta__mdt myMeta = [SELECT Id, Next_Number__c FROM Tax_Receipt_Number_meta__mdt WITH SECURITY_ENFORCED];
        //         myMeta.Next_Number__c ++;
        //         // update myMeta;  
        //     } catch(System.QueryException qe) {
        //         System.debug(qe.getMessage());
        //     }
            
        // }
    }