force-app/main/default/objects/Opportunity/fields/Eligible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Amount__c</fullName>
    <formula>Amount -   Personal_Benefit_Amount_c__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field is automatically calculated on save. This is the Personal Benefit Amount subtracted from the Amount of the opportunity. This is the amount of the donation that CRA deemed tax-receptible</inlineHelpText>
    <label>Eligible_Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/Tax_Receipt__c.object-meta.xml
<CustomObject>
    <description>Tax Receipts.</description>
    <label>Tax Receipt</label>
    <nameField>
        <label>Tax Receipt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Receipt__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <inlineHelpText>The total amount received by the organization</inlineHelpText>
    <label>Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <inlineHelpText>The Address City for who this Tax Receipt is issued to</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/Date_Issued__c.field-meta.xml
<CustomField>
    <fullName>Date_Issued__c</fullName>
    <inlineHelpText>The date this Reciept was issued</inlineHelpText>
    <label>Date Issued</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/Eligible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Amount__c</fullName>
    <inlineHelpText>The amount of the donation that is eligible for charitable tax receipt</inlineHelpText>
    <label>Eligible Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <inlineHelpText>The Opportunity/Donation that this Receipt is related to</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/Personal_Benefit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Personal_Benefit_Amount__c</fullName>
    <inlineHelpText>The amount received by the organization that had a personal benefit or advantage. This portion is ineligible for a tax receipt.</inlineHelpText>
    <label>Personal Benefit Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <inlineHelpText>The address Postal Code for who this Tax Receipt is issued to</inlineHelpText>
    <label>Postal Code</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <inlineHelpText>The address province for who this Tax Receipt is issued to</inlineHelpText>
    <label>Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/Receipt_Rationale_Gift_Description__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Rationale_Gift_Description__c</fullName>
    <inlineHelpText>This is a short description of the gift that will appear on the Receipt. This is useful for describing In-Kind Gift appraisals or sales of Stock</inlineHelpText>
    <label>Receipt Rationale/Gift Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Receipt__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>The Street Address for who this Tax Receipt is issued</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestTaxReceiptCreation.cls
/**
 * @description       : 
 * @author            : kevin@kevinwaites.com
 * @group             : 
 * @last modified on  : 09-26-2020
 * @last modified by  : kevin@kevinwaites.com
 * Modifications Log 
 * Ver   Date         Author                  Modification
 * 1.0   08-11-2020   kevin@kevinwaites.com   Initial Version
**/
@isTest
private class TestTaxReceiptCreation {
    @isTest static void testTaxReceiptCreationWithOpportunity() {
        // Test data setup
        // Create an account with an opportunity, and then try to make a Tax Receipt
        Account acct = new Account(Name='Test Account',
                                BillingStreet='123 here st.',
                                BillingCity='Calgary',
                                BillingState='Alberta',
                                BillingPostalCode='T3E 2E3',
                                BIllingCountry='Canada');
        insert acct;
        Opportunity opp = new Opportunity(  Name = acct.Name + ' Opportunity',
                                            StageName = 'Closed Won',
                                            CloseDate = System.today(),
                                            AccountId = acct.Id,
                                            Amount = 100,
                                            Personal_Benefit_Amount__c = 5,
                                            npsp__In_Kind_Description__c = 'Apex Test Pattern');
        insert opp;

        Tax_Receipt__c myTR = new Tax_Receipt__c (  Opportunity__c = opp.Id,
                                                    Name = 'a',
                                                    Amount__c = 5.00);
        // Perform test
        Test.startTest();
        
        insert myTR;
        Test.stopTest();        

        // Verify
        // Get the newly added Tax_Receipt__c
        Tax_Receipt__c newTR = [ SELECT Id, Name, Amount__c, City__c, Date_Issued__c, Eligible_Amount__c, Personal_Benefit_Amount__c, Postal_Code__c, Province__c, Street__c, Receipt_Rationale_Gift_Description__c FROM Tax_Receipt__c WHERE Id = :myTR.Id LIMIT 1];
        
        // veryify that the Tax Receipt was creted with the right fields from the Opportunity and the Account
        // System.assertEquals( 1, newTR.size(), 'should have found new Tax_Receipt__c' );
        System.assertEquals(opp.Amount, newTR.Amount__c, 'incorrect Amount');
        System.assertEquals(opp.Name + ' - Receipt', newTR.Name, 'incorrect name');
        System.assertEquals(acct.BillingCity, newTR.City__c, 'incorrect City');
        System.assertEquals(System.today(), newTR.Date_Issued__c, 'incorrect Date issued');
        System.assertEquals(opp.Amount - opp.Personal_Benefit_Amount__c, newTR.Eligible_Amount__c, 'incorrect eligible amount');
        System.assertEquals(opp.Personal_Benefit_Amount__c, newTR.Personal_Benefit_Amount__c, 'incorrect personal benefit amount');
        System.assertEquals(acct.BillingPostalCode, newTR.Postal_Code__c, 'incorrect Postal Code');
        System.assertEquals(acct.BillingState, newTR.Province__c, 'incorrect province');
        System.assertEquals(acct.BillingStreet, newTR.Street__c, 'incorrect street');
        System.assertEquals(opp.npsp__In_Kind_Description__c, newTR.Receipt_Rationale_Gift_Description__c, 'incorrect description');
        }
}